spring.application.name=doctor-service

server.port=${PORT:8080}

# Config de la bdd H2 (en memory)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:file:./h2/doctor.db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# Conf de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

#Config  para registrar el microservicio a consul(Servidor de descubrimiento)
#spring.cloud.consul.host=${CONSUL_HOST:localhost}
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.prefer-ip-address=true
#spring.cloud.consul.discovery.service-name=${SERVICE_NAME:doctor-service}
