name: CI-CD Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Fix permisos
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw clean package

      - name: Tests
        run: ./mvnw test

      # 👇 SOLO si todo pasa
      - name: Deploy a Render
        if: success()
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}